name: K8s Minikube Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          container-runtime: docker
          cpus: 2
          memory: 4000m 

      - name: Build Docker Image and Load Image into Minikube
        run: |
          docker build -t niyazautomationqa/playwright-tests:latest .
          minikube image load niyazautomationqa/playwright-tests:latest
      - name: Setup K8s Resources
        run: |
          yarn run pvc
          yarn run k8s

      - name: Wait for Test Execution
        run: |
          kubectl wait --for=condition=complete job/playwright-test-job --timeout=600s || {
            echo "--- POD STATUS ---"
            kubectl get pods
            echo "--- JOB DESCRIPTION ---"
            kubectl describe job playwright-test-job
            echo "--- CONTAINER LOGS ---"
            kubectl logs -l job-name=playwright-test-job
            exit 1
          }
        # kubectl wait --for=condition=failed job/playwright-test-job --timeout=10s

      - name: Retrieve Allure Reports
        if: always()
        run: |
          # Start the retriever pod to access the PVC
          yarn run allure-k8s
          
          # Wait for retriever to be ready
          kubectl wait --for=condition=Ready pod/allure-retriever --timeout=60s
          
          # Copy results from the PVC to the GitHub Runner
          yarn run mnt:allure
          yarn run createallure:k8s

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k8s-allure-report
          path: allure-report/
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true